import { parseAbi } from 'viem';

// Selected deployed interfaces. Tuple order, units and event indexes are ABI-critical.
export const vaultAbi = parseAbi([
  "function maxMint(address receiver) view returns (uint256)",
  "function BOOK() view returns (address)",
  "function accountingStatus() view returns (uint256 cash, uint256 reserved, uint256 pending, bool valid, bool insolvent)",
  "function asset() view returns (address)",
  "function balanceOf(address owner) view returns (uint256 result)",
  "function claimableRedeemRequest(uint256 requestId, address controller) view returns (uint256)",
  "function convertToAssets(uint256 shares) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function deposit(uint256 assets, address receiver, address controller) returns (uint256 shares)",
  "function deposit(uint256 assets, address receiver) returns (uint256 shares)",
  "function maxDeposit(address receiver) view returns (uint256)",
  "function maxRedeem(address controller) view returns (uint256)",
  "function maxWithdraw(address controller) view returns (uint256)",
  "function pendingRedeemRequest(uint256 requestId, address controller) view returns (uint256)",
  "function previewMint(uint256 shares) view returns (uint256 assets)",
  "function previewDeposit(uint256 assets) view returns (uint256 shares)",
  "function requestRedeem(uint256 shares, address controller, address owner) returns (uint256)",
  "function totalAssets() view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function withdraw(uint256 assets, address receiver, address controller) returns (uint256 shares)",
  "error AllowanceOverflow()",
  "error AllowanceUnderflow()",
  "error AssetDeltaMismatch()",
  "error AsyncPreview()",
  "error Busy()",
  "error CashDeficit(uint256 actual, uint256 accounted)",
  "error ClaimAllAssets(uint256 assets)",
  "error DepositMoreThanMax()",
  "error InsufficientAllowance()",
  "error InsufficientBalance()",
  "error InsufficientCredit()",
  "error InvalidAmount()",
  "error InvalidConfiguration()",
  "error InvalidContext()",
  "error InvalidDecimals()",
  "error InvalidFunding()",
  "error InvalidPage()",
  "error InvalidPermit()",
  "error InvalidReceiver()",
  "error InvalidRequest()",
  "error InvalidValuation()",
  "error MintMoreThanMax()",
  "error OrphanedPortfolio()",
  "error Permit2AllowanceIsFixedAtInfinity()",
  "error PermitExpired()",
  "error RedeemMoreThanMax()",
  "error ReservedCash(uint256 available, uint256 requested)",
  "error TotalSupplyOverflow()",
  "error Unauthorized()",
  "error ValuationUnavailable()",
  "error WithdrawMoreThanMax()",
  "function setOperator(address operator, bool approved) returns (bool)",
  "function isOperator(address controller, address operator) view returns (bool)",
  "function checkpointValuation()",
  "function fulfillWithdrawals(uint256 maxTickets)"
]);
